# Generated by Django 3.2.16 on 2023-03-31 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('role', models.IntegerField(default=0, help_text='0 - User; 1 - Admin, 2 - Owner')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=16)),
                ('surname', models.CharField(max_length=32)),
                ('login', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=1024)),
                ('private_password', models.CharField(max_length=1024)),
                ('blocked_times', models.IntegerField(default=0)),
                ('unblock_date', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.role')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('refresh_token', models.CharField(max_length=256)),
                ('access_token', models.CharField(max_length=256)),
                ('type', models.CharField(help_text='public/private', max_length=10)),
                ('online', models.DateTimeField(auto_now=True)),
                ('client', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='user_profile.user')),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
    ]
